// Generated from the authenticated WordPress Appearance > Menus > Main Navigation editor.
// Keep this taxonomy aligned with the Primary menu until category routes are connected.

export interface WordPressMenuGroup {
  label: string;
  items: string[];
}
export interface WordPressMenuSection {
  label: string;
  groups: WordPressMenuGroup[];
}

export const WORDPRESS_MAIN_NAVIGATION: WordPressMenuSection[] = [
  {
    label: "HUMAN DEVELOPMENT",
    groups: [
      {
        label: "Education",
        items: [
          "Scholarships",
          "Grants",
          "Research",
          "Institutions",
          "Vacancies",
          "Primary, Secondary and Vocational Education",
          "Special Education",
          "Publications",
          "Evaluations",
          "Educational Ceremonies",
          "National Youth Service Corps (NYSC)",
          "Completion Rates and Drop-out Rates",
          "Gross and Net Enrolment Rates",
          "Pupil Teacher Ratios",
          "Out-of-School Rate",
          "Teacher Qualification and Learning Assessment",
          "Resource Allocation",
          "Education Attainment",
          "Gender Parity Index (Index)",
        ],
      },
      {
        label: "Health",
        items: [
          "Traditional Medicines",
          "Hospitals and Laboratories",
          "Complex Medical Services",
          "Specialized Care",
          "Basic Health Services",
          "Life Expectancy at Birth",
          "Infant and Under-Five Mortality Rates",
          "Maternal Mortality Ratio",
          "Incidence and Prevalence of Disease",
          "Nutritional Status",
          "Skilled Birth Attendance",
          "Access to Essential Medicine",
          "Hospital Bed Density",
          "Health Workforce Density",
          "Public Health Infrastructure",
          "Health Care Financing Mechanism",
          "Environmental and Social Standards",
          "Mental Health",
          "Reproductive and Sexual Health",
          "Density of Health Care Facilities",
          "Health Expenditure as a Percentage of GDP",
          "Wellbeing",
        ],
      },
    ],
  },
  {
    label: "ECONOMIC DEVELOPMENT",
    groups: [
      {
        label: "Industry, Trade and Investment",
        items: [
          "Manufacturing",
          "Small and Medium Enterprises (SME)",
          "Raw Materials and Mapping",
          "Trade Volumes",
          "Savings, Investment, Credit and other Ratings",
          "Foreign Direct Investments (FDI)",
          "Marine Economy",
          "Service Sector",
          "Other Relevant Indicators",
          "Economic Zones",
        ],
      },
      {
        label: "Agriculture",
        items: [
          "Food Security",
          "Production",
          "Value Addition",
          "Policy Implementation",
          "Life Stock and Aquaculture",
          "Agricultural Allied Ventures",
          "Fruits, Legumes and Nuts",
          "Fiber and Oil Crops",
          "Grains and Cereals",
          "Commercial, Organic and Intensive Agriculture",
          "Food Storage Facility",
          "Mechanization Equipment",
          "Irrigation Farming",
          "Sustainable Agriculture",
          "Cold Logistics",
          "Ecological Zones",
        ],
      },
      {
        label: "Wealth Creation",
        items: [
          "Wealth Redistribution",
          "Poverty Reduction",
          "Supportive Government Policies",
          "Gross Domestic Product (GDP)",
          "Monetary Policy",
          "Budgeting and Debt Financing",
          "Financial Health Performance and Relative Strength Index (RSI)",
          "Economic Volatilities",
          "Human Capital Development",
          "Intervention Programs",
          "Assets and Investments",
          "Savings and Investment",
          "Grants and Aids",
          "Humanitarian Intervention",
        ],
      },
    ],
  },
  {
    label: "INFRASTRUCTURE & CONNECTIVITY",
    groups: [
      {
        label: "Infrastructure",
        items: [
          "Hard Infrastructure",
          "Soft Infrastructure",
          "Critical Infrastructure",
          "Capital Expenditure",
          "Infrastructure Quality",
          "Environmental Sustainability",
        ],
      },
      {
        label: "Transportation",
        items: [
          "Aviation",
          "Road",
          "Rail",
          "Water",
          "Emergencies and Paramedics",
          "Transportation Investigation and Safety Boards",
          "Technical Performance",
          "Economic Performance",
          "Environmental Performance",
          "Social Performance",
          "Infrastructure and Network",
          "Data Collection and Analysis",
        ],
      },
      {
        label: "Energy",
        items: [
          "Decentralized Power Generation",
          "Energy Consumption",
          "Upstream Sector",
          "Downstream Sector",
          "Midstream Sector",
          "Alternative Energy Sources",
          "Training, Monitoring and Development",
          "Gas and Infrastructure",
          "Renewable and Non-Renewable Energy",
        ],
      },
    ],
  },
  {
    label: "TECHNOLOGY & INNOVATION",
    groups: [
      {
        label: "Technology",
        items: [
          "Telecom",
          "Bulk Technology",
          "Phones and Gadgets",
          "Internet Service Providers",
          "Fintech and Banking",
          "Knowledge Transfer",
          "Critical Areas",
          "Digital Economy",
          "Innovation and Technology",
          "Investment in Sustainable Technologies",
          "Internet Penetration",
          "Mobile Phone Penetration",
        ],
      },
    ],
  },
  {
    label: "CULTURE & CREATIVE ECONOMY",
    groups: [
      {
        label: "Entertainment",
        items: [
          "Dual Sports",
          "Music",
          "Arts and Culture",
          "Films and Theaters",
          "Games",
          "Dance and Performances",
          "Comedy",
          "Gossips and Attractions",
          "Lifestyle and Fashion",
          "Mass Media",
          "Team Sports",
          "Individual Sport",
          "Amateur Sports",
        ],
      },
    ],
  },
  {
    label: "GOVERNANCE & LEADERSHIP",
    groups: [
      {
        label: "Leadership",
        items: [
          "Philanthropy",
          "Coporate Social Responsibility",
          "Motivation",
          "Appointment",
          "Statesmanship",
          "Youth Empowerment",
          "Entrepreneurship",
          "Professional Institutes and Associations",
          "Mentorship and Role Models",
          "Trainings, Seminars and Press Briefings",
          "Total Quality Management",
          "Demise",
        ],
      },
      {
        label: "Political Arena",
        items: [
          "Electoral Commission",
          "Political Support and Pressure Groups",
          "Vision, Mission and Score Cards",
          "Political Awareness and Voting Rights",
          "Nigerian Political History and Culture",
          "Political Alliances",
          "Executive Arm of Government",
          "Legislative Arm of Government",
          "Judicial Arm of Government",
          "Election Watchdogs",
          "Constitution, Reforms and Bills",
          "Electioneering and Campaigns",
          "Political Parties and Ideologies",
          "Nigerian Geo-Political Zones",
          "Nigeria Traditional Institutions",
          "Flag Bearer and Party Candidacy",
          "Local Government Council",
          "Governance",
        ],
      },
    ],
  },
  {
    label: "SECURITY & STABILITY",
    groups: [
      {
        label: "Security Alerts",
        items: [
          "Security Agencies",
          "Simple and Miscellaneous Offences",
          "Peace and Conflict Resolutions",
          "Felonies",
          "Misdemeanors",
          "Correctional Services",
          "Enforcement",
          "Community Policing",
          "Crime Alerts",
          "Human Right Violations",
        ],
      },
    ],
  },
  {
    label: "SUSTAINABILITY & DEVELOPMENT",
    groups: [
      {
        label: "Sustainable Development",
        items: [
          "Human Development Index (HDI) and Poverty Rates",
          "Gender Equality",
          "Interconnectedness",
          "Access to Finance",
          "Cultural Values",
          "Access to Clean Water and Sanitation",
          "Housing and Development",
          "Climate Change",
          "Steel Development",
          "Procurement",
          "Deforestation Rates",
          "Population Levels",
          "Health and Education Indicators",
          "Biodiversity",
          "GDP Per Capita and Income Inequality",
          "Institutional Framework",
          "National Planning",
          "Non-Governmental Organizations and Civil Societies",
          "Acquisitions, Collaborations and Partnerships",
          "Trade Unions and Congresses",
        ],
      },
    ],
  },
  {
    label: "INTERNATIONAL & REGIONAL AFFAIRS",
    groups: [
      {
        label: "International and Regional Member Organizations",
        items: [
          "United Nations (UN)",
          "Internatinal Monetary Fund (IMF)",
          "World Bank (WB)",
          "Economic Countries of West African States (ECOWAS)",
          "African Union (AU)",
          "The Lake Chad Basin Commission",
          "The Non-Aligned Movement (NAM)",
          "The Non-Aligned Movement (NAM)",
          "The Organization of Islamic Cooperation (OIC)",
          "The International Fund for Agricultural Development (IFAD)",
          "The World Health Organization (WHO)",
          "International Court of Justice (ICJ)",
          "Permanent Court of Arbitration (PCA)",
          "International Atomic Energy Agency (IAEA)",
          "World Trade Organization (WTO)",
          "United Nations Educational, Scientific and Cultural Organization (UNESCO)",
          "United Nations Children's Fund (UNICEF)",
          "The West African Economic and Monetary Union (WAEMU)",
          "The Commonwealth of Nations",
          "Organization of the Petroleum Exporting Countries (OPEC)",
          "African Development Bank Group (AfDB)",
          "The World Food Programme (WFP)",
          "International Organization for Migration (IOM)",
          "International Finance Corporation (IFC)",
          "International Criminal Court (ICC)",
          "International Labour Organization (ILO)",
          "International Red Cross",
          "Bilateral Agreements",
          "Diplomatic Missions, Embassy and High Commission",
          "Other Affiliate Associations",
          "BRICS",
          "Cultural Exchange",
          "Trade Diplomacy",
          "African Petroleum Producers Organization (APPO)",
          "Gulf of Guinea Commission",
          "New Partnership for Africa Development (NEPAD)",
          "African, Caribbean and Pacific Group of States",
          "Food and Agriculture Organization (FAO)",
          "South –South Cooperation/Partners in Population and Development",
        ],
      },
    ],
  },
] as WordPressMenuSection[];
