import type { Question } from "@/features/question-engine";

export const AGRICULTURE_QUESTIONS: Question[] = [
  {
    id: "contactName",
    type: "short-text",
    title: "What is your full name?",
    helper: "Use the name we should use when following up with you.",
    placeholder: "Your full name",
  },
  {
    id: "contactPhone",
    type: "short-text",
    title: "What phone number should we use?",
    helper: "A Nigerian mobile number is preferred for faster follow-up.",
    placeholder: "+234 800 000 0000",
  },
  {
    id: "contactEmail",
    type: "short-text",
    title: "What is your email address?",
    helper: "We will use this for request updates and confirmations.",
    placeholder: "you@example.com",
  },
  {
    id: "farmLocation",
    type: "short-text",
    title: "Where is the farm or opportunity located?",
    helper: "Tell us the town, state, and country where possible.",
    placeholder: "Ibadan, Oyo State",
  },
  {
    id: "farmSize",
    type: "short-text",
    title: "What is the farm size?",
    helper: "Include the unit, such as acres or hectares.",
    placeholder: "10 hectares",
  },
  {
    id: "serviceType",
    type: "single-choice",
    title: "What do you need help with?",
    choices: [
      { value: "farm-registration", label: "Register a farm" },
      { value: "farm-inputs", label: "Find farm inputs" },
      { value: "buyers", label: "Access buyers or markets" },
      { value: "training", label: "Request training or support" },
      { value: "other", label: "Something else in agriculture" },
    ],
  },
  {
    id: "cropOrLivestock",
    type: "short-text",
    title: "What crop or livestock is involved?",
    helper: "List the main crop, animal, or agricultural activity.",
    placeholder: "Maize, poultry, cassava…",
  },
  {
    id: "quantity",
    type: "short-text",
    title: "What is the estimated quantity or scale?",
    helper: "For example, number of birds, bags of produce, or expected output.",
    placeholder: "2,000 birds or 50 bags",
  },
  {
    id: "timeline",
    type: "single-choice",
    title: "When do you need help?",
    choices: [
      { value: "immediately", label: "Immediately" },
      { value: "within-30-days", label: "Within 30 days" },
      { value: "within-3-months", label: "Within 3 months" },
      { value: "planning", label: "I am planning ahead" },
    ],
  },
  {
    id: "budgetRange",
    type: "short-text",
    title: "What budget range should we consider?",
    helper: "Optional. Include the currency if it is not Nigerian naira.",
    placeholder: "₦500,000 – ₦1,000,000",
    required: false,
  },
  {
    id: "inputsNeeded",
    type: "long-text",
    title: "Which inputs or resources do you need?",
    helper: "Optional. Mention seeds, feed, equipment, finance, logistics, or other needs.",
    placeholder: "Tell us what would make the biggest difference…",
    required: false,
  },
  {
    id: "buyerPreferences",
    type: "long-text",
    title: "Do you have buyer or market preferences?",
    helper: "Optional. Tell us about preferred markets, locations, volumes, or standards.",
    placeholder: "Describe any buyer or market requirements…",
    required: false,
  },
  {
    id: "additionalNotes",
    type: "long-text",
    title: "Anything else we should know?",
    helper: "Optional. Add context that will help the team understand your request.",
    placeholder: "Share any additional context…",
    required: false,
  },
];
